config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "groups#index"
  resources :users, only: [:edit, :update]
  resources :groups, except: :destroy do
    resources :messages, only: [:index, :new, :create]
    collection do
      get  :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord

  validates :name, presence: true

  has_many :users, through: :group_users
  has_many :group_users
  has_many :messages

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  mount_uploader :image, ImageUploader

  validates :body_or_image, presence: true

  private
    def body_or_image
      body.presence or image.presence
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :groups, through: :group_users
  has_many :group_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :authenticate_user!


private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :find_group, only: [:edit, :update]

  before_action :users_groups, only: [:index]

  def index
  end

  def show
  end

  def new
    @group = Group.new
  end

  def search
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%")
    respond_to do |format|
      format.json { render 'new', json: @users }
    end
  end

  def create
    @group = Group.new(create_params)
    if @group.save
      redirect_to root_path, notice: "グループを作成しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update_attributes(create_params)
      redirect_to root_path, notice: "グループを編集しました"
    else
      render :new
    end
  end

  private
  def create_params
    params.require(:group).permit(:name, {user_ids:[]})
  end

  def find_group
    @group = Group.find(params[:id])
  end

  def users_groups
    @groups = current_user.groups
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :set_groups, :users_groups, only: [:new, :create]

  def index
  end

  def new
    @message = Message.new
    @messages = @group.messages
    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @message = current_user.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      flash.now[:alert] = "メッセージを入力してください"
      render :new
    end
  end

private
  def message_params
    params.require(:message).permit(:body, :image, :image_cache, :remove_image).merge(group_id: params[:group_id])
  end

  def set_groups
    @group = Group.find(params[:group_id])
    @users = @group.users
  end

  def users_groups
    @groups = current_user.groups
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    current_user.update(update_params)
    redirect_to root_path
  end

  private
    def update_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_group.html.haml
%li<
= link_to new_group_message_path(group) do
  .sidebar__list__group
    = group.name
  .sidebar__list__text
    - unless group.messages.last == nil
      - if group.messages.last.image?
        %p 画像が投稿されています
      - else
        = group.messages.last.body
    - else
      %p まだメッセージはありません。

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for @group, id: "edit_chat_group", class: "edit_chat_group" do |f|
    - if @group.errors.any?
      .chat-group-form__errors
        %h2
          = "#{ @group.errors.count } 件のエラーが発生しました。"
          %ul
          - @group.errors.full_messages.each do |msg|
            %li
              = msg
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :chat_group_name, "グループ名", class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, placeholder: "グループ名を入力してください", value: "#{@group.name}", id: "chat_group_name", class: "chat-group-form__input"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :chat_group_チャットメンバーを追加, "チャットメンバーを追加", class: "chat-group-form__label"
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input{ class: 'chat-group-form__input', id:'user-search-field', placeholder: '追加したいユーザー名を入力してください', type:'text' }
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :chat_group_チャットメンバー, "チャットメンバー", class: "chat-group-form__label"
      .chat-group-form__field--right
        .chat-group-users.clearfix
        #user-added
          - @group.users.each do |user|
            .chat-group-user.clearfix.js-chat-member#chat-group-user-8
              = f.hidden_field("user_ids][", value: "#{ user.id }")
              %p.chat-group-user__name #{ user.name }
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除

    .chat-group-form__field.clearfix
      .chat-group-form__field--right
        = f.submit "Save", class: "chat-group-form__action-btn", data:{ disable_with: "Save" }

app/views/groups/index.html.haml
!!!
%html
  %body
    .contents
      .sidebar
        .sidebar__profile
          .sidebar__profile__username
            %p #{ current_user.name }
          .sidebar__profile__icons
            = link_to edit_user_path(current_user.id) do
              %i{class: "fa fa-cog"}
            = link_to new_group_path do
              %i{class: "fa fa-edit"}
        .sidebar__list
          %ul
          = render @groups


app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for @group, id: "new_chat_group", class: "new_chat_group" do |f|
    - if @group.errors.any?
      .chat-group-form__errors
        %h2
          = "#{ @group.errors.count } 件のエラーが発生しました。"
          %ul
          - @group.errors.full_messages.each do |msg|
            %li
              = msg
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :chat_group_name, "グループ名", class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, placeholder: "グループ名を入力してください", id: "chat_group_name", class: "chat-group-form__input"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :chat_group_チャットメンバーを追加, "チャットメンバーを追加", class: "chat-group-form__label"
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input{ class: 'chat-group-form__input', id:'user-search-field', placeholder: '追加したいユーザー名を入力してください', type:'text' }
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :chat_group_チャットメンバー, "チャットメンバー", class: "chat-group-form__label"
      .chat-group-form__field--right
        .chat-group-users.clearfix
        #user-added
    .chat-group-form__field.clearfix
      .chat-group-form__field--right
        = f.submit "Save", class: "chat-group-form__action-btn", data:{ disable_with: "Save" }

app/views/layouts/_flash.html.haml
.flash
  - flash.each do |key, value|
    %div{class: "flash__#{key}"}
      .container
        = value

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", http: { equiv: "Content-Type" }}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash'
    = yield

app/views/messages/_message.html.haml
.main__message__up{ data: { id: "#{message.id}" } }
  .main__message__up__name
    = message.user.name
  .main__message__up__date
    = message.created_at.strftime('%Y/%m/%d %H:%M')
- if message.body?
  .main__message__low
    = message.body
- if message.image?
  .main__message__low
    = image_tag "#{ message.image.thumb }"
%br

app/views/messages/new.html.haml
!!!
%html
  %body
    .contents
      = render template: "groups/index"
      .rightcontents
        .header
          .header__info
            %p.header__info__title #{ @group.name }
            .header__info__member
              %p Member：
              %ul
                - @users.each do |user|
                  %li #{ user.name }
          .header__edit
            = link_to "edit", edit_group_path(@group), class: "header__edit__button"
        .main
          .main__messages
            .main__message
            = render @messages
        .form
          .form__box
            = form_for [@group, @message], format: 'json', id: 'new_message' do |f|
              .form__box__left
                .form__box__text
                  = f.text_field :body, placeholder: "type a message", id: "input-body", class: "form__box__text"
                .form__box__pic
                  = f.label :image, fa_icon('picture-o')
                .form__box__pic__botton
                  = f.file_field :image
              .form__box__right
                .form__box__send
                  = f.submit "send", class: "form__send"


app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'